#!/bin/bash

#looping -> for loop

# simple for loop for the items are explicitly given

for i in 1 2 3 4 5
do 
echo "i = $i"
done


echo "---------------------"

# for loop with a range of numbers
for i in {1..4}
do 
echo "i= $i"
done

echo "---------------------"

# for loop with a range of numbers and step
for i in {1..10..2};
do echo "i = $i"; done

echo "---------------------"

echo "files with .sh extension in curr dir"
for file in *.sh
do echo "File: $file"; done


echo "---------------------"
# for loop with a C-style syntax
for (( i =0; i<10; i++ ))
do echo "i= $i"; done


echo "---------------------"